'use strict';

const STORES = [
  {
    id: 'sandboxvr-san-francisco',
    name: 'SandboxVR San Francisco',
    brand: 'SandboxVR',
    city: 'San Francisco',
    country: 'USA',
    region: 'North America',
    description: 'Bay Area sample location used in this scenario app.',
    mapX: 16,
    mapY: 36,
  },
  {
    id: 'sandboxvr-chicago',
    name: 'SandboxVR Chicago',
    brand: 'SandboxVR',
    city: 'Chicago',
    country: 'USA',
    region: 'North America',
    description: 'Midwest sample location used in this scenario app.',
    mapX: 24,
    mapY: 30,
  },
  {
    id: 'sandboxvr-dallas',
    name: 'SandboxVR Dallas',
    brand: 'SandboxVR',
    city: 'Dallas',
    country: 'USA',
    region: 'North America',
    description: 'Texas sample location used in this scenario app.',
    mapX: 22,
    mapY: 40,
  },
  {
    id: 'sandboxvr-london',
    name: 'SandboxVR London',
    brand: 'SandboxVR',
    city: 'London',
    country: 'UK',
    region: 'Europe',
    description: 'London sample location used in this scenario app.',
    mapX: 49,
    mapY: 28,
  },
  {
    id: 'sandboxvr-dublin',
    name: 'SandboxVR Dublin',
    brand: 'SandboxVR',
    city: 'Dublin',
    country: 'Ireland',
    region: 'Europe',
    description: 'Ireland sample location used in this scenario app.',
    mapX: 46,
    mapY: 25,
  },
  {
    id: 'sandboxvr-singapore',
    name: 'SandboxVR Singapore',
    brand: 'SandboxVR',
    city: 'Singapore',
    country: 'Singapore',
    region: 'Asia',
    description: 'Asia sample location used in this scenario app.',
    mapX: 82,
    mapY: 60,
  },
];

module.exports = {
  STORES,
};
